-- 创建一个名为 trade_data 的表
CREATE TABLE IF NOT EXISTS strategy_data_premarket_202502 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date_key TEXT NOT NULL,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    stock_code TEXT NOT NULL,
    stock_name TEXT DEFAULT '',
    stock_rank INTEGER DEFAULT -1,
    block_category TEXT DEFAULT '',
    block_codes TEXT DEFAULT '',
    industry_code TEXT DEFAULT '',
    max_block_category_rank INTEGER DEFAULT -1,
    max_block_code_rank INTEGER DEFAULT -1,
    max_industry_code_rank INTEGER DEFAULT -1,
    is_bottom INTEGER CHECK (is_bottom IN (0, 1)) DEFAULT 0,
    is_broken_plate INTEGER CHECK (is_broken_plate IN (0, 1)) DEFAULT 0,
    is_down_broken INTEGER CHECK (is_down_broken IN (0, 1)) DEFAULT 0,
    is_fall INTEGER CHECK (is_fall IN (0, 1)) DEFAULT 0,
    is_first_down_broken INTEGER CHECK (is_first_down_broken IN (0, 1)) DEFAULT 0,
    is_first_up_broken INTEGER CHECK (is_first_up_broken IN (0, 1)) DEFAULT 0,
    is_gestation_line INTEGER CHECK (is_gestation_line IN (0, 1)) DEFAULT 0,
    is_half INTEGER CHECK (is_half IN (0, 1)) DEFAULT 0,
    is_high INTEGER CHECK (is_high IN (0, 1)) DEFAULT 0,
    is_highest INTEGER CHECK (is_highest IN (0, 1)) DEFAULT 0,
    is_long_shadow INTEGER CHECK (is_long_shadow IN (0, 1)) DEFAULT 0,
    is_low INTEGER CHECK (is_low IN (0, 1)) DEFAULT 0,
    is_medium INTEGER CHECK (is_medium IN (0, 1)) DEFAULT 0,
    is_meso INTEGER CHECK (is_meso IN (0, 1)) DEFAULT 0,
    is_plummet INTEGER CHECK (is_plummet IN (0, 1)) DEFAULT 0,
    is_pre_st INTEGER CHECK (is_pre_st IN (0, 1)) DEFAULT 0,
    is_small_high_open INTEGER CHECK (is_small_high_open IN (0, 1)) DEFAULT 0,
    is_up_broken INTEGER CHECK (is_up_broken IN (0, 1)) DEFAULT 0,
    is_weak INTEGER CHECK (is_weak IN (0, 1)) DEFAULT 0,
    first_limit_up_days INTEGER DEFAULT 0,
    jsjl REAL DEFAULT 0.0,
    cjs REAL DEFAULT 0.0,
    xcjw REAL DEFAULT 0.0,
    jssb REAL DEFAULT 0.0,
    open_pct_rate REAL DEFAULT -100.0,
    open_price REAL DEFAULT -1,
    close_price REAL DEFAULT -1,
    pre_close_price REAL DEFAULT -1,
    next_day_open_price REAL DEFAULT -1,
    next_day_close_price REAL DEFAULT -1,
    next_day_high_price_open_10mins REAL DEFAULT -1,
    next_day_low_price_open_10mins REAL DEFAULT -1,
    next_day_high_price REAL DEFAULT -1,
    next_day_low_price REAL DEFAULT -1,
    in_premarket INTEGER CHECK (in_premarket IN (0, 1)) DEFAULT 0,
    in_premarket_match INTEGER CHECK (in_premarket_match IN (0, 1)) DEFAULT 0,
    mod_code TEXT DEFAULT '',
    mod_name TEXT DEFAULT '',
    mod_short_line_score REAL DEFAULT -100,
    mod_short_line_score_change REAL DEFAULT -100,
    mod_short_line_rank INTEGER DEFAULT -1,
    mod_trend_score REAL DEFAULT -100,
    mod_trend_score_change REAL DEFAULT -100,
    mod_trend_rank INTEGER DEFAULT -1,
    env_json_info TEXT DEFAULT '',
    block_category_info TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (date_key, strategy_name, sub_strategy_name, stock_code)
)



CREATE TABLE IF NOT EXISTS strategy_data_aftermarket_202502 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date_key TEXT NOT NULL,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    stock_code TEXT NOT NULL,
    stock_name TEXT DEFAULT '',
    stock_rank INTEGER DEFAULT -1,
    block_category TEXT DEFAULT '',
    block_codes TEXT DEFAULT '',
    industry_code TEXT DEFAULT '',
    max_block_category_rank INTEGER DEFAULT -1,
    max_block_code_rank INTEGER DEFAULT -1,
    max_industry_code_rank INTEGER DEFAULT -1,
    is_bottom INTEGER CHECK (is_bottom IN (0, 1)) DEFAULT 0,
    is_broken_plate INTEGER CHECK (is_broken_plate IN (0, 1)) DEFAULT 0,
    is_down_broken INTEGER CHECK (is_down_broken IN (0, 1)) DEFAULT 0,
    is_fall INTEGER CHECK (is_fall IN (0, 1)) DEFAULT 0,
    is_first_down_broken INTEGER CHECK (is_first_down_broken IN (0, 1)) DEFAULT 0,
    is_first_up_broken INTEGER CHECK (is_first_up_broken IN (0, 1)) DEFAULT 0,
    is_gestation_line INTEGER CHECK (is_gestation_line IN (0, 1)) DEFAULT 0,
    is_half INTEGER CHECK (is_half IN (0, 1)) DEFAULT 0,
    is_high INTEGER CHECK (is_high IN (0, 1)) DEFAULT 0,
    is_highest INTEGER CHECK (is_highest IN (0, 1)) DEFAULT 0,
    is_long_shadow INTEGER CHECK (is_long_shadow IN (0, 1)) DEFAULT 0,
    is_low INTEGER CHECK (is_low IN (0, 1)) DEFAULT 0,
    is_medium INTEGER CHECK (is_medium IN (0, 1)) DEFAULT 0,
    is_meso INTEGER CHECK (is_meso IN (0, 1)) DEFAULT 0,
    is_plummet INTEGER CHECK (is_plummet IN (0, 1)) DEFAULT 0,
    is_pre_st INTEGER CHECK (is_pre_st IN (0, 1)) DEFAULT 0,
    is_small_high_open INTEGER CHECK (is_small_high_open IN (0, 1)) DEFAULT 0,
    is_up_broken INTEGER CHECK (is_up_broken IN (0, 1)) DEFAULT 0,
    is_weak INTEGER CHECK (is_weak IN (0, 1)) DEFAULT 0,
    first_limit_up_days INTEGER DEFAULT 0,
    jsjl REAL DEFAULT 0.0,
    cjs REAL DEFAULT 0.0,
    xcjw REAL DEFAULT 0.0,
    jssb REAL DEFAULT 0.0,
    open_pct_rate REAL DEFAULT -100.0,
    open_price REAL DEFAULT -1,
    close_price REAL DEFAULT -1,
    pre_close_price REAL DEFAULT -1,
    next_day_open_price REAL DEFAULT -1,
    next_day_close_price REAL DEFAULT -1,
    next_day_high_price_open_10mins REAL DEFAULT -1,
    next_day_low_price_open_10mins REAL DEFAULT -1,
    next_day_high_price REAL DEFAULT -1,
    next_day_low_price REAL DEFAULT -1,
    in_premarket INTEGER CHECK (in_premarket IN (0, 1)) DEFAULT 0,
    in_premarket_match INTEGER CHECK (in_premarket_match IN (0, 1)) DEFAULT 0,
    mod_code TEXT DEFAULT '',
    mod_name TEXT DEFAULT '',
    mod_short_line_score REAL DEFAULT -100,
    mod_short_line_score_change REAL DEFAULT -100,
    mod_short_line_rank INTEGER DEFAULT -1,
    mod_trend_score REAL DEFAULT -100,
    mod_trend_score_change REAL DEFAULT -100,
    mod_trend_rank INTEGER DEFAULT -1,
    env_json_info TEXT DEFAULT '',
    block_category_info TEXT DEFAULT '',
    extra_info TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (date_key, strategy_name, sub_strategy_name, stock_code)
)

CREATE TABLE IF NOT EXISTS trade_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id TEXT NOT NULL,
    date_key TEXT NOT NULL,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    stock_code TEXT NOT NULL,
    buy0_or_sell1 INTEGER DEFAULT -1,
    order_type INTEGER DEFAULT -1,
    order_price REAL DEFAULT -1,
    order_amount REAL DEFAULT -1,
    order_volume INTEGER DEFAULT -1,
    order_time TEXT DEFAULT '',
    order_position REAL DEFAULT -1,
    trade_result INTEGER DEFAULT -1,
    trade_price REAL DEFAULT -1,
    trade_amount REAL DEFAULT -1,
    trade_volume INTEGER DEFAULT -1,
    trade_time TEXT DEFAULT '',
    slip_ratio REAL DEFAULT -1,
    extra_info TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (order_id)
)

CREATE TABLE IF NOT EXISTS strategy_budget (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    budget REAL DEFAULT 0,
    origin_budget REAL DEFAULT 0,
    incrument_budget REAL DEFAULT 0,
    extra_info TEXT DEFAULT '',
    createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS strategy_meta_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    budget REAL DEFAULT 0,
    origin_budget REAL DEFAULT 0,
    incrument_budget REAL DEFAULT 0,
    stop_loss_pct REAL DEFAULT -1,
    take_profit_pct REAL DEFAULT -1,
    max_trade_days INTEGER DEFAULT -1,
    trade_at_open INTEGER DEFAULT 0,
    trade_at_close INTEGER DEFAULT 0,
    trade_at_trading_time INTEGER DEFAULT 0,
    strategy_status INTEGER DEFAULT 0,
    budget_change_log TEXT DEFAULT '',
    profit_loss_pct_log TEXT DEFAULT '',
    profit_loss_log TEXT DEFAULT '',
    extra_info TEXT DEFAULT '',
    win_delta_budget REAL DEFAULT 0,
    loss_delta_budget REAL DEFAULT 0,
    win_budget_alpha REAL DEFAULT 0,
    loss_budget_alpha REAL DEFAULT 0,
    max_budget REAL DEFAULT 0,
    min_budget REAL DEFAULT 0,
    multipy_position INTEGER DEFAULT 0,
    total_profit REAL DEFAULT 0,
    createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (strategy_name)
);



CREATE TABLE IF NOT EXISTS monitor_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    origin_order_id TEXT NOT NULL,
    origin_row_id INTEGER DEFAULT -1,
    date_key TEXT NOT NULL,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    stock_code TEXT NOT NULL,
    trade_result INTEGER DEFAULT -1,
    trade_price REAL DEFAULT -1,
    trade_amount REAL DEFAULT -1,
    trade_volume INTEGER DEFAULT -1,
    trade_time TEXT DEFAULT '',
    trade_date TEXT DEFAULT '',
    profit_pct REAL DEFAULT -1,
    profit REAL DEFAULT -1,
    left_volume INTEGER DEFAULT -1,
    open_price REAL DEFAULT -1,
    last_close_price REAL DEFAULT -1,
    current_price REAL DEFAULT -1,
    monitor_type INTEGER DEFAULT -1,
    stop_loss_price REAL DEFAULT -1,
    take_profit_price REAL DEFAULT -1,
    stop_loss_pct REAL DEFAULT -1,
    take_profit_pct REAL DEFAULT -1,
    max_trade_days INTEGER DEFAULT -1,
    current_trade_days INTEGER DEFAULT -1,
    limit_up_price REAL DEFAULT -1,
    limit_down_price REAL DEFAULT -1,
    sell_order_id TEXT DEFAULT '',
    selled_volume INTEGER DEFAULT 0,
    selled_amount REAL DEFAULT 0,
    selled_price REAL DEFAULT -1,
    extra_info TEXT DEFAULT '',
    monitor_status INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (strategy_name, sub_strategy_name, stock_code, origin_order_id)
)

CREATE TABLE IF NOT EXISTS strategy_monitor_config (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    per_step_tick_gap INTEGER DEFAULT 5,
    cold_start_steps INTEGER DEFAULT 10,
    max_abserve_tick_steps INTEGER DEFAULT 100,
    max_abserce_avg_price_down_steps INTEGER DEFAULT 5,
    stop_profit_open_hc_pct REAL DEFAULT -0.02,
    stop_profit_pct REAL DEFAULT 0,
    dynamic_hc_stop_profit_thres REAL DEFAULT 0,
    static_hc_stop_profit_pct REAL DEFAULT 1,
    last_close_price_hc_pct REAL DEFAULT -0.005,
    last_day_sell_thres REAL DEFAULT 0.06,
    extra_info TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (strategy_name, sub_strategy_name)
)


CREATE TABLE IF NOT EXISTS limit_up_strategy_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    sub_strategy_name TEXT DEFAULT '',
    stock_code TEXT NOT NULL,
    stock_name TEXT DEFAULT '',
    date_key TEXT NOT NULL,
    last_date_key TEXT NOT NULL,
    budget REAL DEFAULT 0,
    c_status INTEGER DEFAULT 0,
    success INTEGER DEFAULT 0,
    success_volumes INTEGER DEFAULT 0,
    success_amount REAL DEFAULT 0,
    order_price REAL DEFAULT 0,
    order_ids TEXT DEFAULT '',
    profit REAL DEFAULT 0,
    profit_pct REAL DEFAULT 0,
    hit_type TEXT DEFAULT "0",
    source TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)