common:
  Host: "p-xcapi.topxlc.com"
Strategies:
  - name: "xiao_cao_dwdx_a"
    type: "小草全盘低位低吸"
    status: 0
    cached: true
    priority: 1
    maxReturnNum: 1
    depends: "xiao_cao_env"
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: true
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "sort_v2"
        step: 2
        desc: "A股全盘绿盘低吸排序"
        logged: false
        params:
          sortId: 40
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: true
            index: 1
            params: {}
          - name: "limiter_filter"
            desc: "限制数量"
            logged: true
            index: 0
            params:
              limit: 3
      - name: "xiao_cao_index_v2"
        step: 3
        desc: "获取明细数据"
        logged: true
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: '{{sort_v2|join(",")}}'
          date: "{{system_time}}"
        filters:
          - name: "change_item_filter"
            index: 0
            desc: "转换格式"
            logged: true
            params: {}
          - name: "stock_type_filter"
            index: 1
            desc: "过滤低位趋势"
            logged: true
            params:
              isLow: 1
          - name: "st_filter"
            index: 2
            desc: "过滤st的股票"
            logged: true
            params: {}
          # - name: "open_pct_filter"
          #   index: 1
          #   desc: "过滤开盘涨幅"
          #   params:
          #     open_pct: -10
          - name: "first_bottom_filter"
            index: 3
            desc: "过滤首次跌停"
            logged: true
            params: {}
          - name: "jw_filter"
            index: 4
            desc: "过滤竞王分"
            logged: true
            params:
              xcjwScore: 200
  - name: "xiao_cao_env"
    type: "小草环境数据"
    status: 1
    cached: true
    priority: 3
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: true
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "build_xiaocao_environment_second_line_v2_dict_simple"
        step: 2
        desc: "构建环境"
        logged: true
        params:
          date: "{{system_time}}"
  - name: "lpdx_first"
    type: "小草全盘绿盘低吸"
    status: 1
    cached: true
    priority: 1
    depends: "xiao_cao_env"
    maxReturnNum: 1
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: false
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: false
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "sort_v2"
        step: 2
        desc: "A股全盘绿盘低吸排序"
        logged: false
        params:
          sortId: 40
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: true
            index: 0
            params: {}
          - name: "limiter_filter"
            desc: "限制数量"
            logged: true
            index: 1
            params:
              limit: 1
      - name: "xiao_cao_index_v2"
        step: 3
        desc: "获取明细数据"
        logged: false
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: '{{sort_v2|join(",")}}'
          date: "{{system_time}}"
        filters:
          - name: "change_item_filter"
            index: 0
            desc: "转换格式"
            logged: true
            params: {}
          - name: "st_filter"
            index: 2
            desc: "过滤st的股票"
            logged: true
            params: {}
          # - name: "open_pct_filter"
          #   index: 1
          #   desc: "过滤开盘涨幅"
          #   params:
          #     open_pct: -10
          - name: "first_bottom_filter"
            index: 3
            desc: "过滤首次跌停"
            logged: true
          - name: "jw_filter"
            index: 4
            desc: "过滤竞王分"
            logged: true
            params:
              xcjwScore: 300
          - name: "item_code_filter"
            index: 5
            desc: "转换格式"
            logged: true
  - name: "xiao_cao_dwdx_d"
    type: "d"
    status: 0
    cached: true
    selectors:
      - name: "check_user_alive"
        step: 1
        desc: "用户状态检查"
        params: {}
      - name: "system_time"
        step: 2
        desc: "获取系统时间"
        params:
          formatter: "%Y-%m-%d"
      - name: "select_block_code"
        step: 3
        desc: "获取方向第一"
        params:
          limit: 1
          score_diff: 20
          category_top: 2
          date: "{{system_time}}"
      - name: "block_codes"
        step: 4
        desc: "获取板块股票"
        params:
          blockCode: "{{select_block_code}}"
          tradeDate: "{{system_time}}"
      - name: "sort_v2"
        step: 5
        desc: "A股全盘绿盘低吸排序"
        params:
          sortId: 40
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            index: 0
            params: {}
          - name: "block_codes_filter"
            desc: "过滤行业板块"
            index: 1
            params:
              limit: 3
      - name: "xiao_cao_index_v2"
        step: 6
        desc: "获取明细数据"
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: "{{sort_v2}}"
          date: "{{system_time}}"
        filters:
          - name: "st_filter"
            index: 0
            desc: "过滤st的股票"
            params:
              is_st: 1
          # - name: "open_pct_filter"
          #   index: 1
          #   desc: "过滤开盘涨幅"
          #   params:
          #     open_pct: -10
          - name: "first_bottom_filter"
            index: 1
            desc: "过滤首次跌停"
            params: {}