common:
  Host: "p-xcapi.topxlc.com"
Strategies:
  - name: "xiao_cao_dwdx_a"
    type: "小草全盘低位低吸"
    status: 1
    cached: true
    priority: 1
    maxReturnNum: 1
    depends: "xiao_cao_env"
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: true
        cached: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: true
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "sort_v2"
        step: 2
        desc: "A股全盘绿盘低吸排序"
        logged: false
        cached: true
        params:
          sortId: 40
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: true
            index: 1
            params: {}
          - name: "limiter_filter"
            desc: "限制数量"
            logged: true
            index: 0
            params:
              limit: 3
      - name: "xiao_cao_index_v2"
        step: 3
        desc: "获取明细数据"
        logged: true
        cached: true
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: '{{sort_v2|join(",")}}'
          date: "{{system_time}}"
        filters:
          - name: "change_item_filter"
            index: 0
            desc: "转换格式"
            logged: true
            params: {}
          - name: "stock_type_filter"
            index: 1
            desc: "过滤低位趋势"
            logged: true
            params:
              isLow: 1
          - name: "st_filter"
            index: 2
            desc: "过滤st的股票"
            logged: true
            params: {}
          # - name: "open_pct_filter"
          #   index: 1
          #   desc: "过滤开盘涨幅"
          #   params:
          #     open_pct: -10
          - name: "first_bottom_filter"
            index: 3
            desc: "过滤首次跌停"
            logged: true
            params: {}
          - name: "jw_filter"
            index: 4
            desc: "过滤竞王分"
            logged: true
            params:
              xcjwScore: 200
  - name: "xiao_mods_info"
    type: "小草模块数据"
    status: 1
    cached: true
    priority: 4
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: false
        params: {}
      - name: "build_xiaocao_mod_dict_all"
        step: 1
        desc: "构建小草模式"
        logged: false
        cached: true
        lruCached: true
        params:
          date: "{{system_time}}"
  - name: "xiao_cao_env"
    type: "小草环境数据"
    status: 1
    cached: true
    priority: 3
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: false
        cached: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: false
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "build_xiaocao_environment_second_line_v2_dict_simple"
        step: 2
        desc: "构建环境"
        logged: false
        cached: true
        params:
          date: "{{system_time}}"
  - name: "lpdx_first"
    type: "小草全盘绿盘低吸"
    status: 1
    cached: true
    priority: 1
    depends: "xiao_cao_env"
    maxReturnNum: 1
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: false
        cached: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: false
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "sort_v2"
        step: 2
        desc: "A股全盘绿盘低吸排序"
        logged: false
        cached: true
        params:
          sortId: 40
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: false
            index: 0
            params: {}
          - name: "limiter_filter"
            desc: "限制数量"
            logged: false
            index: 1
            params:
              limit: 1
      - name: "xiao_cao_index_v2"
        step: 3
        desc: "获取明细数据"
        logged: false
        cached: true
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: '{{sort_v2|join(",")}}'
          date: "{{system_time}}"
        filters:
          - name: "change_item_filter"
            index: 0
            desc: "转换格式"
            logged: true
            params: {}
          - name: "st_filter"
            index: 2
            desc: "过滤st的股票"
            logged: true
            params: {}
          # - name: "open_pct_filter"
          #   index: 1
          #   desc: "过滤开盘涨幅"
          #   params:
          #     open_pct: -10
          - name: "first_bottom_filter"
            index: 3
            desc: "过滤首次跌停"
            logged: true
          - name: "jw_filter"
            index: 4
            desc: "过滤竞王分"
            logged: true
            params:
              xcjwScore: 300
          - name: "item_code_filter"
            index: 5
            desc: "转换格式"
            logged: true
  - name: "低吸"
    type: "小草低吸"
    status: 1
    cached: true
    priority: 1
    maxReturnNum: 1
    depends: "xiao_cao_env,xiao_mods_info"
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: false
        cached: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: false
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "sort_v2"
        step: 2
        desc: "A股全盘绿盘低吸排序"
        logged: false
        cached: true
        params:
          sortId: 40
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: false
            index: 0
            params: {}
      - name: "get_code_by_block_rank"
        step: 3
        desc: "获取股票数据"
        logged: true
        cached: true
        params:
          blockCodeList: ""
          industryBlockCodeList: ""
          categoryCodeList: ""
          exponentCodeList: "{{code}}"
          tradeDate: "{{system_time}}"
          ranks: '{{sort_v2|join(",")}}'
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: false
            index: 0
            params: {}
      - name: "xiao_cao_index_v2"
        step: 4
        desc: "获取明细数据"
        logged: false
        cached: true
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: '{{get_code_by_block_rank|join(",")}}'
          date: "{{system_time}}"
        filters:
          - name: "change_item_filter"
            index: 0
            desc: "转换格式"
            logged: false
            params: {}
          - name: "st_filter"
            index: 2
            desc: "过滤st的股票"
            logged: false
            params: {}
          - name: "first_bottom_filter"
            index: 3
            desc: "过滤首次跌停"
            logged: false
          - name: "dx_filter"
            index: 4
            desc: "过滤竞王分"
            logged: false
            params:
              xcdxScore: 1
          - name: "jw_filter"
            index: 5
            desc: "过滤竞王分"
            logged: false
            params:
              xcjwScore: 100
  - name: "追涨"
    type: "小草追涨"
    status: 1
    cached: true
    priority: 1
    depends: "xiao_cao_env,xiao_mods_info"
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: false
        cached: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: false
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "sort_v2"
        step: 2
        desc: "A股全盘红盘起爆排序"
        logged: false
        cached: true
        params:
          sortId: 39
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: false
            index: 0
            params: {}
      - name: "get_code_by_block_rank"
        step: 3
        desc: "获取股票数据"
        logged: true
        cached: true
        params:
          blockCodeList: ""
          industryBlockCodeList: ""
          categoryCodeList: ""
          exponentCodeList: "{{code}}"
          tradeDate: "{{system_time}}"
          ranks: '{{sort_v2|join(",")}}'
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: false
            index: 0
            params: {}
      - name: "xiao_cao_index_v2"
        step: 4
        desc: "获取明细数据"
        logged: false
        cached: true
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: '{{get_code_by_block_rank|join(",")}}'
          date: "{{system_time}}"
        filters:
          - name: "change_item_filter"
            index: 0
            desc: "转换格式"
            logged: false
            params: {}
          - name: "st_filter"
            index: 2
            desc: "过滤st的股票"
            logged: false
            params: {}
          - name: "qb_filter"
            index: 4
            desc: "过滤起爆分"
            logged: false
            params:
              xcqbScore: 1
          - name: "jw_filter"
            index: 5
            desc: "过滤竞王分"
            logged: false
            params:
              xcjwScore: 100
  - name: "接力"
    type: "小草追涨"
    status: 1
    cached: true
    priority: 1
    depends: "xiao_cao_env,xiao_mods_info"
    selectors:
      - name: "check_user_alive"
        step: 0
        desc: "用户状态检查"
        logged: false
        cached: true
        params: {}
      - name: "system_time"
        step: 1
        desc: "获取系统时间"
        logged: false
        params:
          formatter: "%Y-%m-%d"
        cached: false
      - name: "sort_v2"
        step: 2
        desc: "A股全盘竞王分排序"
        logged: false
        cached: true
        params:
          sortId: 38
          sortType: 1
          hpqbState: 0
          lpdxState: 0
          date: "{{system_time}}"
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: false
            index: 0
            params: {}
      - name: "get_code_by_block_rank"
        step: 3
        desc: "获取股票数据"
        logged: true
        cached: true
        params:
          blockCodeList: ""
          industryBlockCodeList: ""
          categoryCodeList: ""
          exponentCodeList: "{{code}}"
          tradeDate: "{{system_time}}"
          ranks: '{{sort_v2|join(",")}}'
        filters:
          - name: "keys_10cm_filter"
            desc: "过滤key为10cm"
            logged: false
            index: 0
            params: {}
      - name: "xiao_cao_index_v2"
        step: 4
        desc: "获取明细数据"
        logged: false
        cached: true
        params:
          hpqbState: 0
          lpdxState: 0
          stockCodes: '{{get_code_by_block_rank|join(",")}}'
          date: "{{system_time}}"
        filters:
          - name: "change_item_filter"
            index: 0
            desc: "转换格式"
            logged: false
            params: {}
          - name: "st_filter"
            index: 2
            desc: "过滤st的股票"
            logged: false
            params: {}
          - name: "jw_filter"
            index: 4
            desc: "过滤竞王分"
            logged: false
            params:
              xcjwScore: 10
          - name: "jl_filter"
            index: 5
            desc: "过滤接力分"
            logged: false
            params:
              xcjlScore: 1